import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import SessionProviders from "@/providers/SessionProviders";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Chat app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProviders>
        <body
          className={cn("min-h-screen bg-background font-sans antialiased")}
        >
          {children}
          <Toaster richColors duration={5000} />
        </body>
      </SessionProviders>
    </html>
  );
}
